apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "multicalculator.fullname" . }}-frontend
  labels:
    {{- include "multicalculator.labels" . | nindent 4 }}
    role: frontend
    app.kubernetes.io/name: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "multicalculator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: frontend
      role: frontend
  template:
    metadata:
      labels:
        {{- include "multicalculator.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: frontend
        role: frontend
      annotations:
        policy.cilium.io/proxy-visibility: "<Egress/53/UDP/DNS>,<Egress/80/TCP/HTTP>"
    spec:
      serviceAccountName: {{ include "multicalculator.serviceAccountName" . }}
      containers:
        - name: calc-frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.frontendImage }}:{{ .Values.image.frontendTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
          - name: version
            mountPath: /home/node/app/version
{{- if .Values.noProbes }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
{{- end }}
          env: 
            - name: "ENDPOINT"
              value: "http://{{ include "multicalculator.fullname" . }}-backend-svc"
{{- if .Values.introduceRandomResponseLag }}
            - name: "LAGGY"
              value: "{{ .Values.introduceRandomResponseLagValue }}"
            - name: "BUGGY"
              value: "true"
{{- end }}
{{- if .Values.dependencies.useAppInsights }}
            - name: "AIC_STRING"
              valueFrom:
                secretKeyRef:
                  name: {{ include "multicalculator.fullname" . }}-appin-secret
                  key: appinsightskey
{{- end }}
            - name: "PORT"
              value: "8080"
{{- if .Values.dependencies.usePodRedis }}
            - name: "REDIS_HOST"
              value: "localhost"
            - name: "REDIS_AUTH"
              value: "MySuperSecretRedis"
{{- else }}
{{- if .Values.dependencies.useAzureRedis }}
            - name: "REDIS_HOST"
              valueFrom:
                secretKeyRef:
                  name: {{ include "multicalculator.fullname" . }}-redis-secret
                  key: redishostkey
            - name: "REDIS_AUTH"
              valueFrom:
                secretKeyRef:
                  name: {{ include "multicalculator.fullname" . }}-redis-secret
                  key: redisauthkey
{{- end }}
{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- if .Values.dependencies.usePodRedis }}
        - name: redis
          image: redis:6.0
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--requirepass", "MySuperSecretRedis"]
          ports:
            - containerPort: 6379
              name: redis
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}          
      volumes:
      - name: version
        configMap:
          name: {{ include "multicalculator.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "multicalculator.fullname" . }}-backend
  labels:
    {{- include "multicalculator.labels" . | nindent 4 }}
    role: backend
    app.kubernetes.io/name: backend
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "multicalculator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: backend
      role: backend
  template:
    metadata:
      labels:
        {{- include "multicalculator.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: backend
        role: backend
      annotations:
        policy.cilium.io/proxy-visibility: "<Egress/53/UDP/DNS>,<Egress/80/TCP/HTTP>"
    spec:
      serviceAccountName: {{ include "multicalculator.serviceAccountName" . }}
      containers:
        - name: calc-backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.backendImage }}:{{ .Values.image.backendTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
          - name: version
            mountPath: /home/node/app/version
{{- if .Values.noProbes }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
{{- end }}
          env: 
{{- if .Values.introduceRandomResponseLag }}
            - name: "LAGGY"
              value: "{{ .Values.introduceRandomResponseLagValue }}"
            - name: "BUGGY"
              value: "true"
{{- end }}
{{- if .Values.dependencies.useAppInsights }}
            - name: "AIC_STRING"
              valueFrom:
                secretKeyRef:
                  name: {{ include "multicalculator.fullname" . }}-appin-secret
                  key: appinsightskey
{{- end }}
            - name: "PORT"
              value: "8080"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}           
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: version
        configMap:
          name: {{ include "multicalculator.fullname" . }}  
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
{{- if .Values.deployRequester }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "multicalculator.fullname" . }}-requester
  labels:
    {{- include "multicalculator.labels" . | nindent 4 }}
    role: backend
    app.kubernetes.io/name: requester
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "multicalculator.selectorLabels" . | nindent 6 }}
      role: requester
      app.kubernetes.io/name: requester
  template:
    metadata:
      labels:
        {{- include "multicalculator.selectorLabels" . | nindent 8 }}
        role: requester
        app.kubernetes.io/name: requester
    spec:
      serviceAccountName: {{ include "multicalculator.serviceAccountName" . }}
      containers:
        - name: calc-requester
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.requesterImage }}:{{ .Values.image.requesterTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
{{- if .Values.noProbes }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
{{- end }}
          env: 
            - name: "APPLICATIONINSIGHTS_CONNECTION_STRING"
              value: "{{ .Values.dependencies.appInsightsSecretValue }}"
            - name: "ENDPOINT_PORT"
              value: "80"
            - name: "ENDPOINT_HOST"
              value: "{{ include "multicalculator.fullname" . }}-frontend-svc"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}           
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}